---
- name: Bring up MySQL and run Flyway migrations
  hosts: localhost
  connection: local
  tasks:
    - name: Start Docker containers
      command: docker-compose up -d

    - name: Wait for MySQL to be ready
      shell: |
        for i in {1..10}; do
          docker exec mysql mysqladmin ping -h"localhost" --silent && break
          sleep 5
        done

    - name: Run Flyway migration
      command: docker exec flyway flyway migrate
