name: Mysql actions demo
run-name: ${{ github.actor }} is testing out Mysql GitHub Actions 🚀

on: [push]

jobs:
  setup_mysql_database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: subscriptions
          MYSQL_USER: subuser
          MYSQL_PASSWORD: subpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flyway CLI
        run: |
          curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.16.3/flyway-commandline-9.16.3-linux-x64.tar.gz | tar xz
          sudo ln -s $PWD/flyway-*/flyway /usr/local/bin/flyway

      - name: Run initial migrations
        run: |
          flyway -url="jdbc:mysql://localhost:3306/subscriptions?allowPublicKeyRetrieval=true&useSSL=false" \
                 -user=subuser \
                 -password=subpass \
                 -locations=filesystem:./migrations migrate

      - name: Run incremental migrations
        run: |
          flyway -url="jdbc:mysql://localhost:3306/subscriptions?allowPublicKeyRetrieval=true&useSSL=false" \
                 -user=subuser \
                 -password=subpass \
                 -locations=filesystem:./incremental_migrations migrate
